[package]
name = "pcb-schematic"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "Generate human-readable KiCad schematics (.kicad_sch) from pcb-sch netlists"
homepage = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
natord = { workspace = true }
pcb-sch = { workspace = true }
pcb-sexpr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
